### ISSUE TITLE
Runtime Error: `RetryError` During `run_mmlu.py` Execution

### ISSUE THREAD

**Issue by Guoxs** [yanweiyue/AgentPrune#2]
Thank you very much for your nice work! I have been following this research on LLM multi-agent systems, however, I encountered a runtime issue while running the script `run_mmlu.py` with the following command in README.md: 

> python experiments/run_mmlu.py --agent_nums 1 --mode DirectAnswer --decision_method FinalMajorVote --agent_names AdverarialAgent --batch_size 4
 
The program outputs multiple `RetryError` messages during execution, as shown below:

![image](https://github.com/user-attachments/assets/083f675e-9e04-44f4-b5e8-1a3917f73aa9)

Do you have any ideas about what might be causing this issue?

Thank you for your time and help in resolving this!

**Comment by yanweiyue** [comment]
Thank you for bringing this issue to our attention! Your question is valuable and helps us improve the project.

I suspect that the problem might be caused by an error in the LLM API configuration.  The calling method of the API you use may differ from the API used by the project team.

I would recommend modifying the `achat` function in the following file: [gpt_chat.py](https://github.com/yanweiyue/AgentPrune/blob/d95b52bfe75cb2a9795f1da7671bb2de83121045/AgentPrune/llm/gpt_chat.py). Alternatively, you could first create a simple validation script to ensure the API calls to the LLM are functioning as expected.

Please feel free to reach out if you have further questions or need additional clarification.

**Comment by Guoxs** [comment]
Thank you for your kindness help. I try to replace the `achat` function with this version, and it works:
```python
@retry(wait=wait_random_exponential(max=100), stop=stop_after_attempt(3))
async def achat(model: str, msg: List[Dict],):
    client = OpenAI()
    try:
        completion = client.chat.completions.create(
            model=model,
            messages=msg
        )
        
        response_message = completion.choices[0].message.content
        
        if isinstance(response_message, str):
            prompt = "".join([item['content'] for item in msg])
            cost_count(prompt, response_message, model)
            return response_message

    except Exception as e:
        raise RuntimeError(f"Failed to complete the async chat request: {e}")
```
However, `client.chat.completions.create` seems does not support `async` operation, and the experiment runs slow. 

The original version of `achat` in my environment still has problem, and I have checked that the version of `openai` library is the same as that in `requirement.txt`, (openai==1.6.0). 

Do you have any other ideas for this problem? Thanks!

**Comment by yanweiyue** [comment]
We sincerely apologize for the inconvenience caused and greatly appreciate your attention and effort! We suggest you try modifying the provided code as follows:  
```python
import asyncio
import async_timeout
from openai import AsyncOpenAI

@retry(wait=wait_random_exponential(max=100), stop=stop_after_attempt(3))
async def achat(model: str, msg: List[Dict],):
    api_kwargs = dict(api_key = MINE_API_KEYS, base_url = MINE_BASE_URL)
    aclient = AsyncOpenAI(**api_kwargs)
    try:
        async with async_timeout.timeout(1000):
            completion = await aclient.chat.completions.create(model=model,messages=msg)
        response_message = completion.choices[0].message.content
        
        if isinstance(response_message, str):
            prompt = "".join([item['content'] for item in msg])
            cost_count(prompt, response_message, model)
            return response_message

    except Exception as e:
        raise RuntimeError(f"Failed to complete the async chat request: {e}")
```

Once again, thank you for your valuable feedback! We will work on improving the repository code based on the issues you highlighted. If you encounter any other problems, please feel free to let us know.

**Comment by Guoxs** [comment]
Thanks, it works!
